unpackaged/main/default/objects/Account/fields/Esker_Account__c.field-meta.xml
<CustomField>
    <fullName>Esker_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if this account is considered to be sent to Esker</description>
    <label>Esker Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Esker_Account__c.field-meta.xml
<CustomField>
    <fullName>Esker_Account__c</fullName>
    <formula>Account.Esker_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Esker Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Orders.recordType-meta.xml
<RecordType>
    <fullName>Orders</fullName>
    <active>true</active>
    <businessProcess>Orders_Inquiries</businessProcess>
    <description>Orders Record type for CSR Orders</description>
    <label>Orders</label>
</RecordType>

unpackaged/main/default/objects/EskerSettings__c/EskerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Esker Integration Settings</label>
</CustomObject>

unpackaged/main/default/objects/EskerSettings__c/fields/Auto_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Auto_Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether trigger on new email messages is enabled.</description>
    <label>Auto Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EskerSettings__c/fields/Esker_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Esker_Notification_Email__c</fullName>
    <description>Email address to Esker System to receive email messages</description>
    <label>Esker Notification Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/EskerSettings__c/fields/Global_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Global_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the global shutdown switch. Setting to off will disable all integrations with Esker</description>
    <label>Global Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/agi_EmailMessageTriggerTest.cls
@isTest
public class agi_EmailMessageTriggerTest {
    @testSetup
    static void setup(){
		insert new EskerSettings__c(Name='Default', Global_Enabled__c = true, Auto_Trigger_Enabled__c = true, Esker_Notification_Email__c = 'mysalesforcetest@gmail.com');
    }
    
    @isTest
    static void testOrdersTrigger(){
        Account myTestAccount = new Account(Name='MyTestAccount', Esker_Account__c=true);
		insert myTestAccount;
        
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Orders').getRecordTypeId();
        Case aTestCase = new Case(Account=myTestAccount, RecordTypeId=recordTypeId); 
        
        insert aTestCase;
        Id theCaseId = aTestCase.Id;
        System.debug(theCaseId);
        
        Test.startTest();        
        insert new EmailMessage(Incoming=true, FromAddress='mysalesforcetest@gmail.com', ParentId=theCaseId);
		Test.stopTest();
        
        List<EmailMessage> emails = [SELECT Id FROM EmailMessage
                                    WHERE FromAddress='mysalesforcetest@gmail.com'];

        System.assert(theCaseId != null);
        System.assert(emails.size() == 1);
        
    }

    @isTest
    static void testOrdersInquiresTrigger(){
        Account myTestAccount = new Account(Name='MyTestAccount', Esker_Account__c=true);
		insert myTestAccount;
        
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Orders/Inquiries').getRecordTypeId();
        Case aTestCase = new Case(Account=myTestAccount, RecordTypeId=recordTypeId); 
        
        insert aTestCase;
        Id theCaseId = aTestCase.Id;
        System.debug(theCaseId);
        
        Test.startTest();        
        insert new EmailMessage(Incoming=true, FromAddress='mysalesforcetest@gmail.com', ParentId=theCaseId);
		Test.stopTest();
        
        List<EmailMessage> emails = [SELECT Id FROM EmailMessage
                                    WHERE FromAddress='mysalesforcetest@gmail.com'];

        System.assert(theCaseId != null);
        System.assert(emails.size() == 1);
        
    }    
}