unpackaged/main/default/objects/EskerSettings__c/EskerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Esker Integration Settings</label>
</CustomObject>

unpackaged/main/default/objects/EskerSettings__c/fields/Auto_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Auto_Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether trigger on new email messages is enabled.</description>
    <label>Auto Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EskerSettings__c/fields/Esker_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Esker_Notification_Email__c</fullName>
    <description>Email address to Esker System to receive email messages</description>
    <label>Esker Notification Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/EskerSettings__c/fields/Global_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Global_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the global shutdown switch. Setting to off will disable all integrations with Esker</description>
    <label>Global Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/agi_EskerSetupControllerTest.cls
@isTest
public class agi_EskerSetupControllerTest {

    @testSetup
    static void setup(){
		insert new EskerSettings__c(Name='Default', Global_Enabled__c = true, Auto_Trigger_Enabled__c = true, Esker_Notification_Email__c = 'mysalesforcetest@gmail.com');
    }
    @isTest static void testloadpage(){
        agi_EskerSetupController.loadPage();
    }
    @isTest static void testupdateSettings(){
         EskerSettings__c setupRecord = [SELECT Id FROM EskerSettings__c WHERE Name='Default' LIMIT 1];
        agi_EskerSetupController.updateSettings(setupRecord.Id, true, true, 'mysalesforcetest@gmail.com');
    }
    @isTest static void testupdateSettings1(){
        EskerSettings__c setupRecord = [SELECT Id FROM EskerSettings__c WHERE Name='Default' LIMIT 1];
        
        agi_EskerSetupController.updateSettings(setupRecord.Id, false, true, 'mysalesforcetest@gmail.com');
    }
}