unpackaged/main/default/objects/EskerSettings__c/EskerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Esker Integration Settings</label>
</CustomObject>

unpackaged/main/default/objects/EskerSettings__c/fields/Auto_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Auto_Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether trigger on new email messages is enabled.</description>
    <label>Auto Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EskerSettings__c/fields/Esker_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Esker_Notification_Email__c</fullName>
    <description>Email address to Esker System to receive email messages</description>
    <label>Esker Notification Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/EskerSettings__c/fields/Global_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Global_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the global shutdown switch. Setting to off will disable all integrations with Esker</description>
    <label>Global Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/agi_EskerSetupController.cls
public without sharing class agi_EskerSetupController {

    @AuraEnabled
    public static EskerSettings__c loadPage()
    {
        EskerSettings__c theSetting = null;
        
        List<EskerSettings__c> settings = [SELECT Auto_Trigger_Enabled__c,Esker_Notification_Email__c,Global_Enabled__c,Id,Name
                                          	FROM EskerSettings__c
                                          	WHERE Name = 'Default'];
        
        if (settings.size() > 0)
            theSetting = settings[0];
        else {
            throw new NoDataFoundException();
        }

        return theSetting;
    }
    
    @AuraEnabled
    public static void doJack()
    {
        
    }
    
    @AuraEnabled
    public static void updateSettings(String recordId, Boolean intEnabled, Boolean triggerEnabled, String eskerEmail)
    {
        EskerSettings__c settingRecord = [SELECT Id
                                         	FROM EskerSettings__c
                                         	WHERE Id = :recordId
                                         	LIMIT 1];
        
        settingRecord.Auto_Trigger_Enabled__c = triggerEnabled;
        settingRecord.Global_Enabled__c = intEnabled;
        settingRecord.Esker_Notification_Email__c = eskerEmail;
        
        update settingRecord;
    }
    
}